# Configuration MariaDB pour les utilisateurs

# Configuration MongoDB pour les posters (Obiwan Fac)
spring.data.mongodb.uri=mongodb://obiwan.univ-brest.fr:27017/e22002182

# Configuration OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Configuration JWT
jwt.secret=TW9uU3VwZXJTZWNyZXRKV1RRdWlEb2l0RmFpcmVBdU1vaW5zMjU2Qml0cyE=
jwt.expiration=3600

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

