version: '3.8'

services:
  # Base de données pour l'API User/Auth + Poster
  music-db:
    image: mysql:8.0
    container_name: music-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_db
    ports:
      - "12021:3306"
    volumes:
      - music_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base de données MongoDB pour les posters
  mongo-db:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "12022:27017"
    volumes:
      - mongo_db_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: poster_db

  # API Authentication + Poster
  music-api:
    image: gitlab-depinfo.univ-brest.fr:5050/e22002182/apis/authentication-api:v1.0.0
    container_name: music-api
    ports:
      - "12020:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://music-db:3306/music_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/poster_db
    depends_on:
      music-db:
        condition: service_healthy
      mongo-db:
        condition: service_started

volumes:
  music_db_data:
  mongo_db_data:
