# Configuration MariaDB pour les utilisateurs
spring.datasource.url=jdbc:mariadb://obiwan.univ-brest.fr:3306/e22002182_db1
spring.datasource.username=e22002182sql
spring.datasource.password=20ok2UVf
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Configuration MongoDB pour les posters
spring.data.mongodb.uri=mongodb://localhost:27017/poster_db

# Configuration OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Configuration JWT
jwt.secret=TW9uU3VwZXJTZWNyZXRKV1RRdWlEb2l0RmFpcmVBdU1vaW5zMjU2Qml0cyE=
jwt.expiration=3600

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

