spring.application.name=api-gateway

# Port du conteneur API Gateway
server.port=8080

# Configuration CORS pour permettre au frontend Vue.js d'y accéder
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:12020,http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# Routes
# Routage vers l'API d'Authentification / Utilisateurs
spring.cloud.gateway.routes[0].id=authentication-api
spring.cloud.gateway.routes[0].uri=http://authentication-api:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**, /auth/**, /user, /auth, /v3/api-docs/user/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/v3/api-docs/user/(?<segment>.*), /v3/api-docs/$\{segment}

# Routage vers l'API Poster
spring.cloud.gateway.routes[1].id=poster-api
spring.cloud.gateway.routes[1].uri=http://poster-api:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/poster/**, /poster, /v3/api-docs/poster/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/v3/api-docs/poster/(?<segment>.*), /v3/api-docs/$\{segment}
