services:
  # authentication api (servlet simple)
  authentication-api:
    image: gitlab-depinfo.univ-brest.fr:5050/e22002182/apis/authentication-api:latest
    # la version docker de l'image se connecte a la base `authdb:3306/e22002182_db1` avec l'utilisateur `e22002182sql` et le mot de passe `20ok2UVf`
    ports:
      - "12020:8080"
    depends_on:
      - authdb

  authdb:
    # initialisation de la base : `mysql -h 127.0.0.1 -u e22002182sql -p e22002182_db1 < init.sql`
    image: mariadb:11.6.2-ubi9
    restart: unless-stopped
    ports:
      - "12021:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      # chmod 777
      - "./data_auth:/var/lib/mysql"
    environment:
      MARIADB_USER: e22002182sql
      MARIADB_PASSWORD: 20ok2UVf
      MARIADB_ROOT_PASSWORD: 20ok2UVf
      MARIADB_DATABASE: e22002182_db1

  # student-api (appli springboot)
  studentapi:
    image: gitlab-depinfo.univ-brest.fr:5050/e22002182/apis/student-api:latest
    ports:
      - "12022:8080"
    environment:
      spring.datasource.url: jdbc:mysql://studentdb:3306/e22002182_db2
      spring.datasource.username: e22002182sql
      spring.datasource.password: 20ok2UVf
      spring.jpa.database: MYSQL
      spring.jpa.hibernate.ddl-auto: update
    depends_on:
      - studentdb

  studentdb:
    image: mariadb:11.6.2-ubi9
    restart: unless-stopped
    ports:
      - "12023:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      # chmod 777
      - "./data_stud:/var/lib/mysql"
    environment:
      MARIADB_USER: e22002182sql
      MARIADB_PASSWORD: 20ok2UVf
      MARIADB_ROOT_PASSWORD: 20ok2UVf
      MARIADB_DATABASE: e22002182_db2

  # message api (servlet simple) - se connecte a obiwan en mongo
  message-api:
    image: gitlab-depinfo.univ-brest.fr:5050/e22002182/apis/message-api:latest
    ports:
      - "12024:8080"
